#!/usr/local/bin/bash
# /usr/local/bin/leathergoddessofphobos
# from /usr/local/etc/nih-freebsd/modules/frotz/leathergoddessofphobos 

/usr/local/bin/frotz /usr/local/games/frotz/leathergoddessofphobos.z

exit 0
